# This is a template of the config file

# Taken from app configs in telegram developer dashboard
api_id = ""
api_hash = ""

# The chat ID can be found in web.telegram.org - it is "-100{ID in the end of URL}"
chat_id = -100123456789

# Defines the number of days in the past to analyze the user activity
cutoff_days = 90

# Ignore users with these usernames
allowlist = ["sm_zkg_bot"]

[jira]
username = "User.Name"
password = "strongest-jira-password"

# JIRA Hostname
host = "https://myjira.org"

# Ignore telegram users who passed the education but must stay in chat (they are new members of the clan)
tg_allowlist = ["username"]
